import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { paddingTop: 40, paddingHorizontal: 20 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  hamburgerBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e3e3e3' },
  hamburgerLine: { width: 16, height: 2, backgroundColor: '#111', marginVertical: 1 },
  headerGreeting: { flex: 1, marginLeft: 12 },
  // Sidebar styles
  sidebarBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 2000,
  },
  sidebar: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: 280,
    backgroundColor: 'white',
    zIndex: 3000,
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 2, height: 0 },
    paddingTop: 50,
  },
  userInfo: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
  },
  username: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111',
    marginBottom: 4,
  },
  userRole: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  sidebarItem: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  sidebarItemText: {
    fontSize: 16,
    color: '#111',
    fontWeight: '600',
  },
  greeting: { fontSize: 12, color: '#666' },
  userName: { fontSize: 16, fontWeight: '800', color: '#111' },
  cartBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e3e3e3' },
  cartIcon: { fontSize: 18 },
  searchInput: { height: 42, borderRadius: 10, paddingHorizontal: 14, backgroundColor: 'rgba(255,255,255,0.92)', borderWidth: 1, borderColor: '#e3e3e3', marginBottom: 12 },
  // Zomato/Swiggy Style Offers
  offersSection: { 
    marginBottom: 16,
  },
  offersHeader: { 
    marginBottom: 12, 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center',
  },
  offersTitleContainer: { 
    flexDirection: 'row', 
    alignItems: 'center',
    gap: 12,
  },
  offersTitle: { 
    fontSize: 20, 
    fontWeight: '900', 
    color: '#1c1c1c',
    letterSpacing: -0.5,
  },
  liveIndicator: {
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#FF6B6B',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#fff',
  },
  liveText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  seeAllButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
  },
  seeAllText: {
    color: '#666',
    fontSize: 12,
    fontWeight: '700',
  },
  offersList: { 
    paddingRight: 20, 
    paddingLeft: 4,
  },
  offerCardContainer: {
    width: 280,
    height: 180,
  },
  offerCard: { 
    width: '100%', 
    height: '100%', 
    backgroundColor: '#fff',
    borderRadius: 16, 
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    borderWidth: 1,
    borderColor: '#e8e8e8',
    overflow: 'hidden',
  },
  // Enhanced Image Section
  offerImageContainer: {
    height: 110,
    position: 'relative',
    backgroundColor: '#f8f8f8',
  },
  offerImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imageGradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  offerBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  offerBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  urgencyBadgeTop: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(0,0,0,0.8)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  urgencyBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  // Content Section
  offerContentSection: {
    flex: 1,
    padding: 10,
  },
  shopHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  shopInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  shopLogo: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 8,
  },
  shopDetails: {
    flex: 1,
  },
  shopName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1c1c1c',
    marginBottom: 2,
  },
  shopMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#48c479',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
  },
  ratingStar: {
    fontSize: 10,
    marginRight: 2,
  },
  ratingText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#fff',
  },
  deliveryTime: {
    fontSize: 10,
    color: '#696969',
    fontWeight: '600',
  },
  validUntilContainer: {
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  validUntilText: {
    fontSize: 9,
    color: '#696969',
    fontWeight: '600',
  },
  // Offer Details
  offerDetails: {
    marginBottom: 6,
  },
  offerTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1c1c1c',
    marginBottom: 3,
    lineHeight: 16,
  },
  offerDescription: {
    fontSize: 10,
    color: '#696969',
    marginBottom: 6,
    lineHeight: 14,
  },
  priceSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  originalPrice: {
    fontSize: 12,
    color: '#696969',
    textDecorationLine: 'line-through',
    fontWeight: '600',
  },
  newPrice: {
    fontSize: 13,
    color: '#1c1c1c',
    fontWeight: '800',
  },
  offerFooter: { 
    flexDirection: 'row', 
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  ctaText: { 
    fontSize: 11, 
    fontWeight: '700', 
    color: '#FF6B6B',
    letterSpacing: 0.5,
  },
  shimmerEffect: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 20,
  },
  banner: { position: 'relative', borderRadius: 22, overflow: 'hidden', paddingHorizontal: 20, paddingVertical: 20, marginBottom: 0, backgroundColor: 'transparent', height: 180, justifyContent: 'center', width: '92%', alignSelf: 'center' },
  bannerTitle: { fontWeight: '900', color: '#fff', fontSize: 22, lineHeight: 28, maxWidth: '76%', textShadowColor: 'rgba(0,0,0,0.25)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 2 },
  bannerImage: { width: '100%', height: '100%', borderRadius: 22 },
  bannerBgImg: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, width: '100%', height: '100%' },
  welcomeText: { fontSize: 16, fontWeight: '700', marginVertical: 8, color: '#111' },
  titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start', marginBottom: 8 },
  sectionTitle: { fontSize: 20, fontWeight: '900', color: '#111' },
  seeAll: { color: '#16A34A', fontWeight: '700' },
  card: { backgroundColor: 'rgba(255,255,255,0.94)', borderRadius: 12, borderWidth: 1, borderColor: '#e2e2e2' },
  shopImage: { width: '100%', height: 140, borderTopLeftRadius: 12, borderTopRightRadius: 12, backgroundColor: '#f2f2f2' },
  cardContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 12 },
  regularShopName: { fontSize: 16, fontWeight: '800', color: '#111' },
  regularShopMeta: { fontSize: 12, color: '#666', marginTop: 2 },
  shopStatusContainer: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 8,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 60,
    alignItems: 'center',
  },
  statusOpen: {
    backgroundColor: '#28a745',
  },
  statusClosed: {
    backgroundColor: '#dc3545',
  },
  statusText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  statusOpenText: {
    color: '#fff',
  },
  statusClosedText: {
    color: '#fff',
  },
  wishlistBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e3e3e3' },
  wishlistIcon: { fontSize: 18, color: '#666' },
  badge: { position: 'absolute', top: -4, right: -6, backgroundColor: '#16A34A', borderRadius: 8, paddingHorizontal: 5, paddingVertical: 1 },
  badgeText: { color: '#fff', fontSize: 10, fontWeight: '700' },
});
